# Generated by Django 5.0.14 on 2025-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_alias', models.CharField(blank=True, max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('landline', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('alt_email', models.EmailField(blank=True, max_length=254)),
                ('proprietor_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('holding_company', models.CharField(blank=True, max_length=255)),
                ('subsidiary', models.CharField(blank=True, max_length=255)),
                ('established_year', models.IntegerField()),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('ownership_type', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('scst_indicator', models.CharField(blank=True, max_length=50)),
                ('women_enterprise', models.CharField(blank=True, max_length=10)),
                ('application_type', models.CharField(max_length=50)),
                ('products_offered', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=20)),
                ('gst_no', models.CharField(max_length=30)),
                ('gst_type', models.CharField(max_length=50)),
                ('nsic_no', models.CharField(blank=True, max_length=50)),
                ('mse_no', models.CharField(blank=True, max_length=50)),
                ('approved_vendor_of', models.CharField(blank=True, max_length=255)),
                ('nsic_valid_date', models.DateField(blank=True, null=True)),
                ('mse_valid_date', models.DateField(blank=True, null=True)),
                ('gem_no', models.CharField(blank=True, max_length=50)),
                ('nsic_permanent', models.CharField(blank=True, max_length=10)),
                ('ssi_permanent', models.CharField(blank=True, max_length=10)),
                ('iso9000', models.CharField(blank=True, max_length=10)),
                ('iso14000', models.CharField(blank=True, max_length=10)),
                ('iso18000', models.CharField(blank=True, max_length=10)),
                ('cin_no', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_city', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=15)),
                ('account_no', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('turnover_year1', models.IntegerField()),
                ('turnover_amt1', models.CharField(max_length=50)),
                ('turnover_year2', models.IntegerField()),
                ('turnover_amt2', models.CharField(max_length=50)),
                ('turnover_year3', models.IntegerField()),
                ('turnover_amt3', models.CharField(max_length=50)),
                ('declaration', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
