# Generated by Django 5.0.14 on 2025-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='mse_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/mse_certificates/'),
        ),
    ]
