# Generated by Django 5.0.14 on 2025-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_rename_mse_certificate_vendorregistration_msme_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
